# fly.toml file generated for eibot on 2022-12-03T23:52:06Z

app = "eibot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
